export const mockEmployees = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    position: "Software Engineer",
    department: "Engineering",
    hireDate: "2022-01-15",
    bio: "Passionate software engineer with a focus on web development.",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    position: "HR Manager",
    department: "Human Resources",
    hireDate: "2021-05-20",
    bio: "Experienced HR professional dedicated to employee well-being.",
  },
]

export const mockLeaveRequests = [
  {
    id: "101",
    employeeId: "1",
    type: "annual_leave",
    startDate: "2024-03-15",
    endDate: "2024-03-20",
    reason: "Family vacation",
    status: "approved",
    submittedAt: "2024-01-05",
    priority: "normal",
  },
  {
    id: "102",
    employeeId: "1",
    type: "sick_leave",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    reason: "Flu symptoms",
    status: "rejected",
    submittedAt: "2024-01-03",
    rejectionReason: "Insufficient documentation",
    priority: "normal",
  },
  {
    id: "103",
    employeeId: "2",
    type: "personal_leave",
    startDate: "2024-04-10",
    endDate: "2024-04-12",
    reason: "Personal matters",
    status: "pending",
    submittedAt: "2024-01-08",
    priority: "urgent",
  },
  {
    id: "104",
    employeeId: "1",
    type: "annual_leave",
    startDate: "2024-05-01",
    endDate: "2024-05-05",
    reason: "Spring break",
    status: "pending",
    submittedAt: "2024-01-12",
    priority: "normal",
  },
  {
    id: "105",
    employeeId: "2",
    type: "annual_leave",
    startDate: "2024-06-10",
    endDate: "2024-06-14",
    reason: "Summer vacation",
    status: "approved",
    submittedAt: "2024-01-15",
    priority: "normal",
  },
]
